apiVersion: v1
kind: Service
metadata:
  name: todolb
  labels:
    app: todolb
spec:
  type: LoadBalancer
  selector:
    app: todoapp
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP

